### ISSUE TITLE
HTTP/1.1 500 Internal Server Error with Apache httpd-2.4.57 + mod_proxy_fcgi

### ISSUE THREAD

**Issue by olivier-fs** [kamchatka-volcano/asyncgi#2]
Hi!

[I'm switching this issue from fcgi_responder to asyncgi]

More info.
I used Wireshark to capture FCGI packets, and check difference between (webserver, fcgi lib) combos

fcgi_responder built/used as in fcgi_responder repo : The lib does not add header(s), the application is in charge to add meaningful headers if required

- nginx + : Always OK, even with non-RFC compliant header (i.e. HTTP/1.1 200 OK instead of Status: 200 OK) or no header at all.
- httpd + : Works only with Status: 200 OK.

fcgi_responder built/used as in asyncgi repo : Headers are added by the libs, the application only sends "HELLO WORLD"

- nginx : Always OK, 
- http: Always KO

3 headers are added by the libs:
HTTP/1.1 200 OK
Status: 200 OK
ContentType: text/html

I guess the "HTTP/1.1 200 OK" is what makes httpd/mod_proxy_fcgi unhappy.

Also, if I
    response.send("Content-Type: text/plain\r\n\r\nHELLO WORLD");
instead of 
    response.send("HELLO WORLD");

the ""Content-Type: text/plain\r\n\r\n" is inserted in the response body not in the headers (i.e. the string param to send is the full response body)

```
$ curl -v http://127.0.0.1/fcgi/home
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80
> GET /fcgi/home HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/8.3.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.25.2
< Date: Sat, 30 Sep 2023 12:31:47 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< ContentType: text/html
<
Content-Type: text/plain

HELLO WORLD* Connection #0 to host 127.0.0.1 left intact
```

As a summary
- I think "HTTP/1.1 200 OK" should be removed
- May be the application should be the only one in charge for setting Content-Type (with asyncgi/fcgi_responder possibly adding text/plain if no content-type is defined, but IMHO I don't like it)

Additional question : How to properly set header(s) in response header not body ?

Regards

**Comment by kamchatka-volcano** [comment]
Hi, I've also tested it with apache2 and caddy and arrived at the same conclusion - I will remove HTTP status headers. Actually I had some issues with NGINX without the CGI `Status:` header, but unfortunately I solved it by using it together with the HTTP status, instead of replacing it.
Also, I fixed the typo in the Content-Type header, and yes, it is automatically generated when it's not provided by the user, I won't be changing this logic for now.

>How to properly set header(s) in response header not body ?

`asyncgi::Response::send()` takes either `asyncgi::http::Response` or `asyncgi::fastcgi::Response` structures. `fastcgi::Response` - is a raw string response like from the examples of `fcgi_responder`. `http::Response` has many different overloads taking status code, content type, cookies, headers and the body. You can check them in `asyncgi/http/response.h` header, which is provided by https://github.com/kamchatka-volcano/hot_teacup library and bundled by CMake in the `http` directory during the configuration stage.
`asyncgi::Response` also has an overload taking a parameter pack and constructing `http::Response` with it. 
So, 
```response.send(asyncgi::http::Response{http::ResponseStatus::_404_Not_Found, "Not found"});```
is the same as
```response.send(http::ResponseStatus::_404_Not_Found, "Not found");```

So when you use `response.send("HELLO WORLD");` it creates the `http::Response` object with a constructor that takes a single string (the response body) and generates the `200 OK` status and `Content-Type: text/html` headers.

I will release the new version with fixes soon.

**Comment by kamchatka-volcano** [comment]
This should work fine now. Please update to [v0.3.2](https://github.com/kamchatka-volcano/asyncgi/releases/tag/v0.3.2)

**Comment by olivier-fs** [comment]
Updated to latest 0.3.2.
Tested with httpd + mod_proxy_fcgi : Works great ! Thank you for fixing this (and be damn quick) 👍
```
$ curl -v http://127.0.0.1:8080/fcgi/home
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080
> GET /fcgi/home HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/8.3.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 01 Oct 2023 09:35:40 GMT
< Server: Apache/2.4.57 (Win64)
< Transfer-Encoding: chunked
< Content-Type: text/html
<
Hello world* Connection #0 to host 127.0.0.1 left intact
```

My point on using httpd:
nginx beats httpd hands down on static content, on classic webserver role serving dynamic content, but mod_proxy_fcgi is much faster than nginx fastcgi module...
At least on my boxes (be it modest Dell XPS 13 laptop or real servers.)
I don't know why... Maybe some nginx fastcgi param could be tuned better, but my setup is done like in nginx docs for serving PHP (only _true_ devs use C++ backend hahaha).

Thanks for clearing things up on sending headers (BTW nice componentization of request handling in hot_teacup). I admit I was a bit lazy at not RTFM first.

Now I may be dumb but I couldn't send headers right from the asyncgi::Response& response.
I managed to do it by creating a local http::Response.
```
    router.route("/fcgi/headers", http::RequestMethod::Get)
		.process(
#if 0 // KO error C2039: 'addHeader': is not a member of 'asyncgi::Response'
			[](const asyncgi::Request&, asyncgi::Response& response)
			{
				response.addHeader(http::Header{"Custom-Header-1", "Header1"});
				response.send("RESPONSE WITH HEADERS");
			}
#elif 0 // KO error C2039: 'addHeader': is not a member of 'fastcgi::Response'
			[](const asyncgi::Request&, fastcgi::Response& response)
			{
				response.addHeader(http::Header{"Custom-Header-1", "Header1"});
				response.send("RESPONSE WITH HEADERS");
			}
#elif 0	// KO error C2039: 'send': is not a member of 'asyncgi::http::Response'		
			[](const asyncgi::Request&, http::Response& response)
			{
				response.addHeader(http::Header{"Custom-Header-1", "Header1"});
				response.send("RESPONSE WITH HEADERS");
			}
#elif 1	// OK! but requires to create a local http::Response
			[](const asyncgi::Request&, asyncgi::Response& response)
			{
				std::vector<http::Header> headers;
				headers.emplace_back("Custom-Header-1", "Header1");
				headers.emplace_back("Custom-Header-2", "Header2");
				http::Response http_response("RESPONSE WITH HEADERS", "text/html", {}, headers);
				response.send(http_response);
			}
#endif			
		);
```

I may be missing something.
(It might be worth an example_sending_headers.cpp : much more beginner friendly than digging in hot_teacup headers)

(Minor remark on http::Response here : May be headers should be before cookies, as it's more likely to send headers with no cookie than cookies with no header, and the default param value can't play here... Nothing really annoying, just usability).

But it definitely does the job
```
$ curl -v http://127.0.0.1:8080/fcgi/headers
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080
> GET /fcgi/headers HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/8.3.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 01 Oct 2023 09:42:41 GMT
< Server: Apache/2.4.57 (Win64)
< Custom-Header-1: Header1
< Custom-Header-2: Header2
< Transfer-Encoding: chunked
< Content-Type: text/html
<
RESPONSE WITH HEADERS* Connection #0 to host 127.0.0.1 left intact

$ curl -v http://127.0.0.1/fcgi/headers
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80
> GET /fcgi/headers HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/8.3.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.25.2
< Date: Sun, 01 Oct 2023 09:42:47 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Custom-Header-1: Header1
< Custom-Header-2: Header2
<
RESPONSE WITH HEADERS* Connection #0 to host 127.0.0.1 left intact
```

Thanks again for all your work.
I'm a happy user of classic C fcgi lib since the begining of Apache (mod_fastcgi from the OpenMarket WebServer days...).
mod_fastcgi is unmaintained but has been replaced.
But it's first time that I see a real replacement for fcgi : all other codebases (cgi, cgicc, fastcgipp, boost.cgi etc.) are either dead or non-functional or non-portable.
Even Wt Web Toolkit relies on old fcgi lib when not using embedded asio web server.
Better : no more needs for cgi-fcgi or spawn-fcgi or alike to do the "close stdin" trick of fcgi lib to sort CGI from FastCGI : External servers can be launched really standalone.

P.S. 
When I have time i'll do tests with httpd mod_fcgid instead of mod_proxy_fcgi, to launch backend processes on demand rather than external prelaunched processes.

**Comment by olivier-fs** [comment]
< ContentType: text/html

I couldn' see it when it was in front of my eyes.
Maybe _that_ was the real problem with httpd : rejects invalid header when nginx ignores it.

**Comment by kamchatka-volcano** [comment]
Thanks for the kind words and it's nice to see someone excited about FastCGI technology :) 

>I couldn't send headers right from the asyncgi::Response& response.

Why would you expect to be able to do it? The public interface of `asyncgi::Response` is just:
```
    template<typename... TArgs>
    void send(TArgs... args)
    {
        auto response = http::Response{std::forward<TArgs>(args)...};
        send(response);
    }

    void redirect(
            std::string path,
            http::RedirectType redirectType = http::RedirectType::Found,
            std::vector<http::Cookie> cookies = {},
            std::vector<http::Header> headers = {});
    void send(const http::Response& response);
    void send(fastcgi::Response response);
    bool isSent() const;
```
So you can either send an `http::Reponse` or a `fastcgi::Response`, that's by design. `redirect` is somewhat out of place there, but this signature while being the most convenient one was in a conflict with another `http::Response` constructor that's why I've placed it here as a helper method. I might try to rethink it later.

That means that your last choice is correct, but it can be simplified like this:
```
[](const asyncgi::Request&, asyncgi::Response& response)
{
  response.send("RESPONSE WITH HEADERS",  
      http::Cookies{}, 
      http::Headers{ {"Custom-Header-1", "Header1"}, {"Custom-Header-2", "Header2"}});
}
```
Currently, I don't have time to invest in a fully documented API. So, even if you've read the README, it's useful to check the public interface of the library headers. ;)

>as it's more likely to send headers with no cookie than cookies with no header

For my use cases it's the other way around) I have some projects where I use cookies for a simple session implementation (as seen in the [guestbook demo](https://asyncgi-guestbook.eelnet.org)), but I haven't used any custom headers so far.
